# Generated by Django 5.1.6 on 2025-05-04 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("developer", models.CharField(max_length=100)),
                ("release_year", models.PositiveIntegerField()),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "rental_price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "rental_price_per_day",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="static/media"),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_processor", models.CharField(max_length=100)),
                ("min_ram_gb", models.PositiveIntegerField()),
                ("min_gpu", models.CharField(max_length=100)),
                ("rec_processor", models.CharField(blank=True, max_length=100)),
                ("rec_ram_gb", models.PositiveIntegerField(blank=True, null=True)),
                ("rec_gpu", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GameCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.category"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "category")},
            },
        ),
        migrations.AddField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(
                related_name="games", through="games.GameCategory", to="games.category"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="requirements",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game",
                to="games.gamerequirements",
            ),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_to",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 ⭐"),
                            (2, "2 ⭐"),
                            (3, "3 ⭐"),
                            (4, "4 ⭐"),
                            (5, "5 ⭐"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game")},
            },
        ),
    ]
