version: '3.9'

services:
  web:
    build: .
    container_name: gameshare-app
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn gameshare.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
