services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/mysql

  web:
    env_file:
      - .env.dev
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
