version: '3.9'

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: gameshare
      MYSQL_USER: root
      MYSQL_PASSWORD: Sanpancracio01
      MYSQL_ROOT_PASSWORD: Sanpancracio01
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: gameshare
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000  # Primero migrar
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_ENV: production  # Esta variable indica que es producción

volumes:
  db_data:
